import{clamp,damp}from'./core.js';
export class AudioRig{
  constructor(){this.ctx=null;this.master=null;this.sfx=null;this.engineBus=null;this.nodes=null;this.speed=0;this.boost=0;this.muted=localStorage.getItem('neon-apex-muted')==='true'}
  async unlock(){if(!this.ctx)this.build();if(this.ctx.state==='suspended')await this.ctx.resume();this.applyMute()}
  toggle(){this.muted=!this.muted;localStorage.setItem('neon-apex-muted',String(this.muted));this.applyMute();return this.muted}
  setPaused(paused){if(!this.ctx||!this.engineBus)return;this.engineBus.gain.setTargetAtTime(paused?.025:.42,this.ctx.currentTime,.06)}
  update(ratio,boosting,dt){if(!this.ctx||!this.nodes)return;this.speed=damp(this.speed,clamp(ratio,0,1.35),5,dt);this.boost=damp(this.boost,boosting?1:0,boosting?12:5,dt);const n=this.nodes,t=this.ctx.currentTime,p=42+this.speed*94+this.boost*38;n.engine.frequency.setTargetAtTime(p,t,.035);n.harmonic.frequency.setTargetAtTime(p*2.01,t,.04);n.engineGain.gain.setTargetAtTime(.07+this.speed*.15,t,.05);n.harmonicGain.gain.setTargetAtTime(.015+this.speed*.055+this.boost*.04,t,.06);n.filter.frequency.setTargetAtTime(350+this.speed*1700+this.boost*900,t,.05);n.windGain.gain.setTargetAtTime(Math.max(0,this.speed-.12)*.15,t,.08);n.windFilter.frequency.setTargetAtTime(500+this.speed*3200,t,.07)}
  cue(name){if(!this.ctx||this.ctx.state!=='running')return;const map={ui:[520,.065,.05,'triangle',1.18],countdown:[285,.12,.09,'square',.9],go:[520,.15,.12,'sawtooth',1.45],boost:[118,.35,.11,'sawtooth',2.8],pickup:[720,.12,.08,'sine',1.4],repair:[430,.18,.08,'sine',1.55],impact:[86,.28,.17,'sawtooth',.42],warning:[215,.16,.065,'square',.75],finish:[392,.5,.1,'triangle',2],wreck:[130,.75,.18,'sawtooth',.22]};const v=map[name];if(v)this.tone(...v);if(name==='boost')this.noise(.35,.1,2200);if(name==='impact'||name==='wreck')this.noise(name==='wreck'?.8:.24,name==='wreck'?.27:.18,name==='wreck'?520:950);if(name==='finish'){[523,659,784].forEach((f,i)=>setTimeout(()=>this.tone(f,.23,.08,'triangle',1.07),90*(i+1)))}}
  build(){const C=window.AudioContext||window.webkitAudioContext;this.ctx=new C({latencyHint:'interactive'});const c=this.ctx;this.master=c.createGain();this.sfx=c.createGain();this.engineBus=c.createGain();const comp=c.createDynamicsCompressor();this.master.gain.value=this.muted?0:.7;this.sfx.gain.value=.72;this.engineBus.gain.value=.42;comp.threshold.value=-14;comp.ratio.value=5;comp.attack.value=.003;comp.release.value=.2;this.sfx.connect(comp);this.engineBus.connect(comp);comp.connect(this.master).connect(c.destination);const filter=c.createBiquadFilter();filter.type='lowpass';filter.frequency.value=500;filter.Q.value=1.8;const engine=c.createOscillator(),harmonic=c.createOscillator(),eg=c.createGain(),hg=c.createGain();engine.type='sawtooth';engine.frequency.value=42;harmonic.type='triangle';harmonic.frequency.value=86;eg.gain.value=.07;hg.gain.value=.015;engine.connect(eg).connect(filter);harmonic.connect(hg).connect(filter);filter.connect(this.engineBus);const buf=c.createBuffer(1,c.sampleRate*2,c.sampleRate),data=buf.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;const wind=c.createBufferSource(),wf=c.createBiquadFilter(),wg=c.createGain();wind.buffer=buf;wind.loop=true;wf.type='bandpass';wf.frequency.value=900;wf.Q.value=.7;wg.gain.value=0;wind.connect(wf).connect(wg).connect(this.engineBus);engine.start();harmonic.start();wind.start();this.nodes={engine,harmonic,engineGain:eg,harmonicGain:hg,filter,windGain:wg,windFilter:wf}}
  applyMute(){if(this.ctx&&this.master)this.master.gain.setTargetAtTime(this.muted?0:.7,this.ctx.currentTime,.04)}
  tone(freq,duration,gainValue,type,endPitch=1){const c=this.ctx,o=c.createOscillator(),g=c.createGain(),now=c.currentTime;o.type=type;o.frequency.setValueAtTime(freq,now);o.frequency.exponentialRampToValueAtTime(Math.max(24,freq*endPitch),now+duration);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(gainValue,now+Math.min(.018,duration*.2));g.gain.exponentialRampToValueAtTime(.0001,now+duration);o.connect(g).connect(this.sfx);o.start(now);o.stop(now+duration+.03)}
  noise(duration,gainValue,cutoff){const c=this.ctx,len=Math.floor(c.sampleRate*duration),buf=c.createBuffer(1,len,c.sampleRate),d=buf.getChannelData(0);for(let i=0;i<len;i++){const e=1-i/len;d[i]=(Math.random()*2-1)*e*e}const s=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();s.buffer=buf;f.type='lowpass';f.frequency.value=cutoff;g.gain.value=gainValue;s.connect(f).connect(g).connect(this.sfx);s.start()}
}
