import*as THREE from'three';
import{EffectComposer}from'three/addons/postprocessing/EffectComposer.js';
import{RenderPass}from'three/addons/postprocessing/RenderPass.js';
import{UnrealBloomPass}from'three/addons/postprocessing/UnrealBloomPass.js';
import{OutputPass}from'three/addons/postprocessing/OutputPass.js';
import{AudioRig}from'./audio.js';
import{TAU,clamp,saturate,damp,wrap01,shortestTrackDelta,formatTime,ordinalPosition,seededRandom}from'./core.js';

const $=id=>{const e=document.getElementById(id);if(!e)throw Error(`Missing #${id}`);return e};
const MOBILE='(pointer:coarse),(max-width:900px)',LAPS=3,ROAD_HALF=9,MAX_SPEED=84,BOOST_SPEED=116;
const tmpV=new THREE.Vector3(),tmpQ=new THREE.Quaternion(),tmpM=new THREE.Matrix4(),tmpC=new THREE.Color();

class Input{
  constructor(commands){this.held=new Set;this.pointers=new Map;this.events=0;this.last=null;this.commands=commands;this.keys={ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right',ArrowUp:'throttle',KeyW:'throttle',ArrowDown:'brake',KeyS:'brake',Space:'boost',ShiftLeft:'drift',ShiftRight:'drift'};window.addEventListener('keydown',e=>this.down(e),{passive:false});window.addEventListener('keyup',e=>this.up(e),{passive:false});window.addEventListener('blur',()=>this.reset());document.addEventListener('visibilitychange',()=>document.hidden&&this.reset());for(const b of document.querySelectorAll('[data-action]')){b.addEventListener('pointerdown',e=>this.pointerDown(e),{passive:false});for(const name of['pointerup','pointercancel','lostpointercapture'])b.addEventListener(name,e=>this.pointerUp(e),{passive:false});b.addEventListener('contextmenu',e=>e.preventDefault())}}
  down(e){const a=this.keys[e.code];if(a){e.preventDefault();this.held.add(a);return}if(e.repeat)return;if(e.code==='Escape'||e.code==='KeyP'){e.preventDefault();this.commands.pause()}else if(e.code==='KeyR')this.commands.restart();else if(e.code==='KeyM')this.commands.mute();else if(e.code==='KeyQ')this.commands.quality()}
  up(e){const a=this.keys[e.code];if(a){e.preventDefault();this.held.delete(a)}}
  pointerDown(e){e.preventDefault();const b=e.currentTarget,a=b.dataset.action;if(!a)return;this.events++;this.last=a;this.pointers.set(e.pointerId,a);this.held.add(a);b.classList.add('pressed');if(e.pointerType!=='touch')b.setPointerCapture?.(e.pointerId)}
  pointerUp(e){e.preventDefault();const b=e.currentTarget,a=this.pointers.get(e.pointerId)||b.dataset.action;b.classList.remove('pressed');this.pointers.delete(e.pointerId);if(a&&![...this.pointers.values()].includes(a))this.held.delete(a)}
  sample(){let steer=(this.held.has('right')?1:0)-(this.held.has('left')?1:0),throttle=this.held.has('throttle')?1:0,brake=this.held.has('brake')?1:0,boost=this.held.has('boost'),drift=this.held.has('drift');const pad=[...(navigator.getGamepads?.()||[])].find(Boolean);if(pad){const a=pad.axes[0]||0;if(Math.abs(a)>.12)steer=clamp(a,-1,1);throttle=Math.max(throttle,pad.buttons[7]?.value||0,pad.buttons[0]?.pressed?1:0);brake=Math.max(brake,pad.buttons[6]?.value||0,pad.buttons[1]?.pressed?1:0);boost||=!!(pad.buttons[2]?.pressed||pad.buttons[5]?.pressed);drift||=!!pad.buttons[4]?.pressed}return{steer,throttle,brake,boost,drift}}
  reset(){this.held.clear();this.pointers.clear();document.querySelectorAll('[data-action]').forEach(b=>b.classList.remove('pressed'))}
  diagnostics(){return{pointerEvents:this.events,lastIntent:this.last,held:[...this.held]}}
}

function canvasTexture(draw,w=512,h=512){const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');draw(x,w,h);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.anisotropy=8;return t}
function roadTexture(){const t=canvasTexture((x,w,h)=>{x.fillStyle='#111722';x.fillRect(0,0,w,h);const g=x.createLinearGradient(0,0,w,0);g.addColorStop(0,'#1c2532');g.addColorStop(.18,'#0c121d');g.addColorStop(.5,'#171e2a');g.addColorStop(.82,'#0c121d');g.addColorStop(1,'#1c2532');x.fillStyle=g;x.fillRect(0,0,w,h);for(let i=0;i<1200;i++){const a=Math.random()*.09;x.fillStyle=`rgba(150,190,210,${a})`;x.fillRect(Math.random()*w,Math.random()*h,1+Math.random()*2,1)}x.fillStyle='rgba(80,235,255,.72)';x.fillRect(10,0,4,h);x.fillRect(w-14,0,4,h)},512,1024);t.repeat.set(1,42);return t}
function windowTexture(){const t=canvasTexture((x,w,h)=>{x.fillStyle='#09101d';x.fillRect(0,0,w,h);for(let y=16;y<h;y+=30)for(let z=14;z<w;z+=28){const on=Math.random()>.34;x.fillStyle=on?(Math.random()>.35?'#39d9e8':'#a460ff'):'#101c2a';x.fillRect(z,y,12,13)}},256,512);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(1,2);return t}
function glowTexture(){return canvasTexture((x,w,h)=>{const g=x.createRadialGradient(w/2,h/2,0,w/2,h/2,w/2);g.addColorStop(0,'rgba(255,255,255,1)');g.addColorStop(.2,'rgba(130,245,255,.9)');g.addColorStop(1,'rgba(40,180,255,0)');x.fillStyle=g;x.fillRect(0,0,w,h)},128,128)}
function orient(group,frame){tmpM.makeBasis(frame.side,frame.up,frame.tangent);group.quaternion.setFromRotationMatrix(tmpM)}

class ParticleField{
  constructor(scene,quality){this.max=quality==='high'?520:280;this.pos=new Float32Array(this.max*3);this.col=new Float32Array(this.max*3);this.vel=Array.from({length:this.max},()=>new THREE.Vector3);this.life=new Float32Array(this.max);this.cursor=0;const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(this.pos,3));g.setAttribute('color',new THREE.BufferAttribute(this.col,3));const m=new THREE.PointsMaterial({size:.55,map:glowTexture(),vertexColors:true,transparent:true,opacity:.9,depthWrite:false,blending:THREE.AdditiveBlending,sizeAttenuation:true});this.points=new THREE.Points(g,m);this.points.frustumCulled=false;scene.add(this.points)}
  burst(position,color,count=24,power=9,direction=new THREE.Vector3(0,1,0)){tmpC.set(color);for(let k=0;k<count;k++){const i=this.cursor++%this.max,j=i*3;this.pos[j]=position.x;this.pos[j+1]=position.y;this.pos[j+2]=position.z;this.col[j]=tmpC.r;this.col[j+1]=tmpC.g;this.col[j+2]=tmpC.b;this.vel[i].set((Math.random()-.5)*power,(Math.random()*.75+.15)*power,(Math.random()-.5)*power).addScaledVector(direction,power*(.2+Math.random()*.5));this.life[i]=.45+Math.random()*.65}}
  update(dt){for(let i=0;i<this.max;i++){if(this.life[i]<=0)continue;this.life[i]-=dt;const j=i*3,v=this.vel[i];v.y-=5*dt;v.multiplyScalar(Math.exp(-1.8*dt));this.pos[j]+=v.x*dt;this.pos[j+1]+=v.y*dt;this.pos[j+2]+=v.z*dt;if(this.life[i]<=0)this.pos[j+1]=-999}this.points.geometry.attributes.position.needsUpdate=true}
}

class World{
  constructor(scene,quality){this.scene=scene;this.quality=quality;this.rand=seededRandom(7319);this.obstacles=[];this.pickups=[];this.pads=[];this.rivals=[];this.trackPoints=[];this.offsetCache=new Map;this.materials={cyan:new THREE.MeshBasicMaterial({color:0x50f4ff,toneMapped:false}),mag:new THREE.MeshBasicMaterial({color:0xff4edb,toneMapped:false}),orange:new THREE.MeshBasicMaterial({color:0xffad45,toneMapped:false})};this.buildCurve();this.buildSky();this.buildLights();this.buildTrack();this.buildWorld();this.player=this.vehicle(0x55f4ff,0xff9851,true);const colors=[[0xff4edb,0x884eff],[0xff9c45,0xff3c5d],[0x56ff8d,0x33aaff],[0xa878ff,0xff4edb],[0xeefaff,0x55ccff]];for(const c of colors)this.rivals.push(this.vehicle(c[0],c[1],false));this.particles=new ParticleField(scene,quality)}
  buildCurve(){const p=[[-88,15,-5],[-68,20,-78],[-8,27,-118],[72,23,-110],[128,17,-58],[130,21,20],[88,32,88],[22,27,120],[-56,19,108],[-116,13,62],[-135,11,3],[-118,15,-45]].map(v=>new THREE.Vector3(...v));this.curve=new THREE.CatmullRomCurve3(p,true,'catmullrom',.45);this.length=this.curve.getLength();for(let i=0;i<720;i++)this.trackPoints.push(this.curve.getPointAt(i/720))}
  frame(u){u=wrap01(u);const center=this.curve.getPointAt(u),tangent=this.curve.getTangentAt(u).normalize(),worldUp=new THREE.Vector3(0,1,0),side=new THREE.Vector3().crossVectors(worldUp,tangent).normalize(),up=new THREE.Vector3().crossVectors(tangent,side).normalize();const bank=Math.sin(u*TAU*3.1)*.075+Math.sin(u*TAU*7.2)*.028;side.applyAxisAngle(tangent,bank);up.applyAxisAngle(tangent,bank);return{center,tangent,side,up}}
  offsetCurve(offset,y=0){const key=`${offset}:${y}`;if(this.offsetCache.has(key))return this.offsetCache.get(key);const pts=[];for(let i=0;i<240;i++){const f=this.frame(i/240);pts.push(f.center.clone().addScaledVector(f.side,offset).addScaledVector(f.up,y))}const c=new THREE.CatmullRomCurve3(pts,true,'catmullrom',.5);this.offsetCache.set(key,c);return c}
  buildSky(){this.scene.background=new THREE.Color(0x040611);this.scene.fog=new THREE.FogExp2(0x070817,.0018);const g=new THREE.BufferGeometry(),count=this.quality==='high'?2200:1200,pos=new Float32Array(count*3),col=new Float32Array(count*3);for(let i=0;i<count;i++){const r=300+this.rand()*650,a=this.rand()*TAU,b=Math.acos(this.rand()*2-1);pos[i*3]=Math.sin(b)*Math.cos(a)*r;pos[i*3+1]=Math.cos(b)*r+150;pos[i*3+2]=Math.sin(b)*Math.sin(a)*r;const tint=this.rand();col[i*3]=.55+tint*.45;col[i*3+1]=.7+tint*.3;col[i*3+2]=1}g.setAttribute('position',new THREE.BufferAttribute(pos,3));g.setAttribute('color',new THREE.BufferAttribute(col,3));this.stars=new THREE.Points(g,new THREE.PointsMaterial({size:1.1,vertexColors:true,transparent:true,opacity:.85,depthWrite:false}));this.scene.add(this.stars);const planet=new THREE.Mesh(new THREE.SphereGeometry(53,48,24),new THREE.MeshStandardMaterial({color:0x44286d,emissive:0x130d2a,roughness:.9}));planet.position.set(-270,130,-430);this.scene.add(planet);const ring=new THREE.Mesh(new THREE.RingGeometry(68,88,96),new THREE.MeshBasicMaterial({color:0x8f69ce,transparent:true,opacity:.28,side:THREE.DoubleSide,depthWrite:false}));ring.position.copy(planet.position);ring.rotation.set(1.25,.3,.2);this.scene.add(ring)}
  buildLights(){this.scene.add(new THREE.HemisphereLight(0x728dff,0x080611,1.25));const sun=new THREE.DirectionalLight(0xd9e5ff,2.2);sun.position.set(-80,180,-100);sun.castShadow=this.quality==='high';sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-120;sun.shadow.camera.right=120;sun.shadow.camera.top=120;sun.shadow.camera.bottom=-120;this.scene.add(sun);this.playerLight=new THREE.PointLight(0x53efff,4.2,35,2);this.scene.add(this.playerLight)}
  ribbon(offsetA,offsetB,y,material,segments=720){const pos=[],norm=[],uv=[],idx=[];for(let i=0;i<=segments;i++){const u=i/segments,f=this.frame(u);for(const o of[offsetA,offsetB]){const p=f.center.clone().addScaledVector(f.side,o).addScaledVector(f.up,y);pos.push(p.x,p.y,p.z);norm.push(f.up.x,f.up.y,f.up.z);uv.push(o===offsetA?0:1,u)}}for(let i=0;i<segments;i++){const a=i*2;idx.push(a,a+2,a+1,a+2,a+3,a+1)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(norm,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(idx);g.computeBoundingSphere();const mesh=new THREE.Mesh(g,material);mesh.receiveShadow=true;this.scene.add(mesh);return mesh}
  buildTrack(){const roadMat=new THREE.MeshStandardMaterial({color:0x283342,map:roadTexture(),roughness:.7,metalness:.45,emissive:0x050914,emissiveIntensity:.6});this.road=this.ribbon(-ROAD_HALF,ROAD_HALF,0,roadMat);const under=new THREE.MeshStandardMaterial({color:0x07101d,metalness:.75,roughness:.5,side:THREE.DoubleSide});this.ribbon(-ROAD_HALF-.8,ROAD_HALF+.8,-.5,under,480);for(const [o,c]of[[-ROAD_HALF-.55,0x45eaff],[ROAD_HALF+.55,0xff4edb]]){const tube=new THREE.Mesh(new THREE.TubeGeometry(this.offsetCurve(o,.35),480,.12,7,true),new THREE.MeshBasicMaterial({color:c,toneMapped:false}));this.scene.add(tube);const glow=new THREE.Mesh(new THREE.TubeGeometry(this.offsetCurve(o,.34),360,.32,6,true),new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:.16,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false}));this.scene.add(glow)}const markerGeo=new THREE.BoxGeometry(.12,.035,2.4),markerMat=new THREE.MeshBasicMaterial({color:0x8cfaff,transparent:true,opacity:.68,toneMapped:false}),count=210,inst=new THREE.InstancedMesh(markerGeo,markerMat,count);for(let i=0;i<count;i++){const u=i/count,f=this.frame(u),lane=(i%3-1)*3;tmpM.makeBasis(f.side,f.up,f.tangent);tmpM.setPosition(f.center.clone().addScaledVector(f.side,lane).addScaledVector(f.up,.06));inst.setMatrixAt(i,tmpM)}this.scene.add(inst)}
  buildWorld(){this.buildSupports();this.buildCity();this.buildCheckpoints();this.buildPads();this.buildObstacles();this.buildPickups();this.buildBillboards()}
  buildSupports(){const pillarMat=new THREE.MeshStandardMaterial({color:0x101b29,metalness:.78,roughness:.42}),capMat=new THREE.MeshBasicMaterial({color:0x1d8fa5,toneMapped:false});for(let i=0;i<48;i++){const u=i/48,f=this.frame(u),baseY=-24,h=Math.max(8,f.center.y-baseY),g=new THREE.Group(),pillar=new THREE.Mesh(new THREE.CylinderGeometry(.65,1.7,h,8),pillarMat);pillar.position.y=-h/2-.45;pillar.castShadow=this.quality==='high';g.add(pillar);const cap=new THREE.Mesh(new THREE.CylinderGeometry(1.8,1.8,.18,12),capMat);cap.position.y=-.6;g.add(cap);g.position.copy(f.center).addScaledVector(f.up,-.15).addScaledVector(f.side,(i%2?1:-1)*6.4);this.scene.add(g)}}
  buildCity(){const geo=new THREE.BoxGeometry(1,1,1),mat=new THREE.MeshStandardMaterial({color:0x182436,map:windowTexture(),emissiveMap:windowTexture(),emissive:0x2855a2,emissiveIntensity:.8,metalness:.5,roughness:.55}),count=this.quality==='high'?210:130,inst=new THREE.InstancedMesh(geo,mat,count);inst.castShadow=false;inst.receiveShadow=true;let made=0,tries=0;while(made<count&&tries++<5000){const x=(this.rand()-.5)*520,z=(this.rand()-.5)*520;let close=false;for(let k=0;k<this.trackPoints.length;k+=24){const p=this.trackPoints[k];if(Math.hypot(x-p.x,z-p.z)<32){close=true;break}}if(close)continue;const h=8+this.rand()*54,w=4+this.rand()*10,d=4+this.rand()*10,y=-20+h/2;tmpM.compose(new THREE.Vector3(x,y,z),new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,1,0),this.rand()*TAU),new THREE.Vector3(w,h,d));inst.setMatrixAt(made++,tmpM)}inst.count=made;this.city=inst;this.scene.add(inst);const ground=new THREE.Mesh(new THREE.CircleGeometry(390,96),new THREE.MeshStandardMaterial({color:0x050912,emissive:0x050a17,roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-20;this.scene.add(ground)}
  placeObject(root,u,lane=0,y=0){const f=this.frame(u);root.position.copy(f.center).addScaledVector(f.side,lane).addScaledVector(f.up,y);orient(root,f);root.userData={u,lane};this.scene.add(root);return f}
  buildCheckpoints(){for(const [i,u]of[0,.25,.5,.75].entries()){const root=new THREE.Group(),mat=new THREE.MeshStandardMaterial({color:0x17283a,metalness:.8,roughness:.3,emissive:i%2?0x2b0f48:0x073a45,emissiveIntensity:1}),glow=new THREE.MeshBasicMaterial({color:i%2?0xff4edb:0x52f4ff,toneMapped:false});for(const x of[-10.2,10.2]){const p=new THREE.Mesh(new THREE.BoxGeometry(.65,8,.8),mat);p.position.set(x,4,0);root.add(p);const l=new THREE.Mesh(new THREE.BoxGeometry(.11,6.5,.9),glow);l.position.set(x*.98,4,.05);root.add(l)}const top=new THREE.Mesh(new THREE.BoxGeometry(20.9,.65,.9),mat);top.position.y=8;root.add(top);const line=new THREE.Mesh(new THREE.BoxGeometry(18.8,.12,1),glow);line.position.y=7.8;root.add(line);this.placeObject(root,u,0,.2)}}
  buildPads(){for(const [i,u]of[.08,.19,.34,.47,.61,.74,.88].entries()){const lane=[-4,0,4][i%3],root=new THREE.Group(),base=new THREE.Mesh(new THREE.BoxGeometry(5.4,.08,6.8),new THREE.MeshBasicMaterial({color:0x321d55,transparent:true,opacity:.65}));root.add(base);for(let k=-2;k<=2;k++){const strip=new THREE.Mesh(new THREE.BoxGeometry(.5,.1,5.8),new THREE.MeshBasicMaterial({color:k%2?0xff4edb:0x7560ff,toneMapped:false}));strip.position.x=k*.9;root.add(strip)}this.placeObject(root,u,lane,.07);this.pads.push({u,lane,root,lap:-1})}}
  buildObstacles(){const data=[[.13,-4,'barrier'],[.23,3,'drones'],[.3,-1,'mine'],[.41,4,'barrier'],[.52,-4,'mine'],[.58,1,'drones'],[.69,4,'barrier'],[.79,-2,'drones'],[.84,2,'mine'],[.93,-4,'barrier']];for(const [i,[u,lane,kind]]of data.entries()){const root=new THREE.Group();if(kind==='barrier'){for(const x of[-1.15,1.15]){const p=new THREE.Mesh(new THREE.BoxGeometry(1.8,3.5,.65),new THREE.MeshStandardMaterial({color:0x3b0c22,emissive:0xff244d,emissiveIntensity:2.2,metalness:.5,roughness:.35}));p.position.set(x,1.75,0);root.add(p)}const beam=new THREE.Mesh(new THREE.BoxGeometry(4.6,.22,.5),new THREE.MeshBasicMaterial({color:0xff3b62,toneMapped:false}));beam.position.y=2.2;root.add(beam)}else if(kind==='mine'){const core=new THREE.Mesh(new THREE.IcosahedronGeometry(1.1,1),new THREE.MeshStandardMaterial({color:0x32101f,emissive:0xff315c,emissiveIntensity:3,metalness:.8,roughness:.2}));core.position.y=1.3;root.add(core);for(let k=0;k<3;k++){const ring=new THREE.Mesh(new THREE.TorusGeometry(1.6+k*.25,.06,6,32),new THREE.MeshBasicMaterial({color:0xff4268,toneMapped:false}));ring.rotation.set(k*.8,k*.55,0);ring.position.y=1.3;root.add(ring)}}else{for(let k=-1;k<=1;k++){const d=new THREE.Mesh(new THREE.OctahedronGeometry(.75,0),new THREE.MeshStandardMaterial({color:0x411b5d,emissive:0xbc43ff,emissiveIntensity:2.5,metalness:.7,roughness:.25}));d.position.set(k*1.65,1.7+Math.abs(k)*.4,0);root.add(d)}}this.placeObject(root,u,lane,.15);this.obstacles.push({u,lane,kind,root,index:i})}}
  buildPickups(){for(const [i,u]of[.105,.17,.27,.37,.455,.56,.645,.72,.815,.9,.965].entries()){const kind=i%4===2?'repair':'energy',lane=[-4,0,4,2,-2][i%5],root=new THREE.Group(),color=kind==='repair'?0x52f4ff:0xff4edb,mat=new THREE.MeshStandardMaterial({color:0xffffff,emissive:color,emissiveIntensity:2.5,metalness:.4,roughness:.15});const core=new THREE.Mesh(kind==='repair'?new THREE.OctahedronGeometry(.72,0):new THREE.IcosahedronGeometry(.68,1),mat);root.add(core);const ring=new THREE.Mesh(new THREE.TorusGeometry(1.05,.08,8,32),new THREE.MeshBasicMaterial({color,toneMapped:false}));ring.rotation.x=Math.PI/2;root.add(ring);this.placeObject(root,u,lane,1.8);this.pickups.push({u,lane,kind,root,lap:-1})}}
  buildBillboards(){const labels=['NEON APEX','ION RACING','SECTOR 07','VELOCITY LEAGUE'];for(let i=0;i<12;i++){const c=document.createElement('canvas');c.width=512;c.height=160;const x=c.getContext('2d');x.fillStyle='rgba(5,10,24,.86)';x.fillRect(0,0,c.width,c.height);x.strokeStyle=i%2?'#ff4edb':'#52f4ff';x.lineWidth=8;x.strokeRect(5,5,502,150);x.fillStyle='#effcff';x.font='900 58px Arial';x.textAlign='center';x.textBaseline='middle';x.fillText(labels[i%labels.length],256,82);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const mesh=new THREE.Mesh(new THREE.PlaneGeometry(11,3.4),new THREE.MeshBasicMaterial({map:tex,transparent:true,side:THREE.DoubleSide,toneMapped:false}));this.placeObject(mesh,.04+i/12,(i%2?1:-1)*13,4.8);mesh.rotation.y+=i%2?Math.PI:0}}
  vehicle(primary,accent,player){const root=new THREE.Group(),body=new THREE.Group();root.add(body);const hullMat=new THREE.MeshStandardMaterial({color:player?0x182635:primary,metalness:.82,roughness:.24,emissive:new THREE.Color(primary).multiplyScalar(.13),emissiveIntensity:1});const accentMat=new THREE.MeshBasicMaterial({color:accent,toneMapped:false}),dark=new THREE.MeshStandardMaterial({color:0x050913,metalness:.85,roughness:.28});const hull=new THREE.Mesh(new THREE.ConeGeometry(1.55,5.2,4,1),hullMat);hull.rotation.x=Math.PI/2;hull.position.z=.25;hull.scale.z=.9;hull.castShadow=true;body.add(hull);const spine=new THREE.Mesh(new THREE.BoxGeometry(.75,.32,4.9),dark);spine.position.set(0,.15,-.1);body.add(spine);const cockpit=new THREE.Mesh(new THREE.SphereGeometry(.78,24,12),new THREE.MeshPhysicalMaterial({color:0x183853,emissive:0x06324a,emissiveIntensity:1.2,metalness:.25,roughness:.12,transmission:.3,transparent:true,opacity:.86}));cockpit.scale.set(.9,.5,1.45);cockpit.position.set(0,.45,.5);body.add(cockpit);for(const x of[-1,1]){const wing=new THREE.Mesh(new THREE.BoxGeometry(2.15,.16,2.6),hullMat);wing.position.set(x*1.45,-.02,-.25);wing.rotation.y=x*.18;body.add(wing);const edge=new THREE.Mesh(new THREE.BoxGeometry(1.8,.07,.16),accentMat);edge.position.set(x*1.7,.08,.65);edge.rotation.y=x*.18;body.add(edge)}const thrusters=[],pads=[];for(const x of[-.78,.78]){const ring=new THREE.Mesh(new THREE.TorusGeometry(.36,.11,8,20),dark);ring.rotation.x=Math.PI/2;ring.position.set(x,0,-2.45);body.add(ring);const flame=new THREE.Mesh(new THREE.ConeGeometry(.27,2.3,10,1,true),new THREE.MeshBasicMaterial({color:accent,transparent:true,opacity:.75,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false}));flame.rotation.x=-Math.PI/2;flame.position.set(x,0,-3.35);body.add(flame);thrusters.push(flame)}for(const x of[-1.6,1.6]){const pad=new THREE.Mesh(new THREE.TorusGeometry(.48,.1,8,24),accentMat);pad.rotation.x=Math.PI/2;pad.position.set(x,-.3,-.25);body.add(pad);pads.push(pad)}const shield=new THREE.Mesh(new THREE.SphereGeometry(3.1,24,12),new THREE.MeshBasicMaterial({color:0x5beaff,transparent:true,opacity:0,wireframe:true,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false}));shield.scale.set(1,.42,1.25);body.add(shield);this.scene.add(root);return{root,body,thrusters,pads,shield,primary,accent}}
  placeVehicle(v,u,lane,hover=1.18){const f=this.frame(u);v.root.position.copy(f.center).addScaledVector(f.side,lane).addScaledVector(f.up,hover);orient(v.root,f);v.root.userData.u=u;return f}
  playerVisual(ratio,steer,boosting,hit,dt){const v=this.player;v.body.position.y=Math.sin(performance.now()*.006)*.045;v.body.rotation.z=damp(v.body.rotation.z,-steer*.15,8,dt);v.body.rotation.x=damp(v.body.rotation.x,ratio*.035,5,dt);v.thrusters.forEach((f,i)=>{f.scale.y=damp(f.scale.y,.7+ratio*.9+(boosting?1.2:0)+Math.sin(performance.now()*.02+i)*.08,10,dt);f.material.opacity=.48+ratio*.25+(boosting?.25:0)});v.pads.forEach((p,i)=>p.rotation.z+=dt*(1.6+i*.2));v.shield.material.opacity=hit*.22;this.playerLight.position.copy(v.root.position).add(new THREE.Vector3(0,2,0))}
  update(t,dt){this.stars.rotation.y=t*.003;for(const [i,p]of this.pads.entries()){p.root.children.forEach((c,k)=>{if(c.material?.emissiveIntensity!==undefined)c.material.emissiveIntensity=1.4+Math.sin(t*6+i+k)*.5});p.root.position.y+=Math.sin(t*4+i)*.001}for(const [i,p]of this.pickups.entries()){p.root.rotation.y+=dt*(1.4+i*.03);p.root.children[1].rotation.z+=dt*1.8;p.root.position.y+=Math.sin(t*3+i)*.0015}for(const [i,o]of this.obstacles.entries()){if(o.kind==='mine')o.root.rotation.z+=dt*.9;else if(o.kind==='drones')o.root.children.forEach((d,k)=>d.position.y=1.7+Math.sin(t*3+i+k)*.4)}this.particles.update(dt)}
}

class Game{
  constructor(){this.qa=new URLSearchParams(location.search).get('qa')==='1';this.mobile=matchMedia(MOBILE).matches;this.reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;this.quality=this.initialQuality();this.mount=$('scene');this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(66,1,.12,1300);this.renderer=new THREE.WebGLRenderer({antialias:this.quality==='high',powerPreference:'high-performance',stencil:false});this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.08;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.info.autoReset=false;this.mount.appendChild(this.renderer.domElement);this.world=new World(this.scene,this.quality);this.composer=new EffectComposer(this.renderer);this.composer.addPass(new RenderPass(this.scene,this.camera));this.bloom=new UnrealBloomPass(new THREE.Vector2(1,1),.68,.52,.74);this.composer.addPass(this.bloom);this.composer.addPass(new OutputPass());this.audio=new AudioRig();this.input=new Input({pause:()=>this.togglePause(),restart:()=>this.restart(),mute:()=>this.toggleMute(),quality:()=>this.toggleQuality()});this.dom=this.domRefs();this.ctx=this.dom.minimap.getContext('2d');this.sectorEls=[...document.querySelectorAll('#sectors i')];this.state='menu';this.beforePause='racing';this.last=performance.now();this.lastRender=0;this.frameCount=0;this.toastTimer=0;this.warningTimer=0;this.shake=0;this.hitFlash=0;this.hitCooldown=0;this.obstacleLap=new Map;this.best=Number(localStorage.getItem('neon-apex-best'))||0;this.camTarget=new THREE.Vector3();this.camPos=new THREE.Vector3();this.lookPos=new THREE.Vector3();this.rivals=this.world.rivals.map((visual,i)=>({visual,distance:21-i*4,speed:0,cruise:[68.4,70.1,66.8,71.8,69.2][i],lane:[-4.6,2.7,4.5,-1.6,.8][i],phase:i*1.72}));this.bounds=this.trackBounds();this.bind();this.applyQuality();this.reset();this.menuPresentation();this.resize();this.installDiagnostics();addEventListener('resize',()=>this.resize(),{passive:true});document.addEventListener('visibilitychange',()=>document.hidden&&(this.state==='racing'||this.state==='countdown')&&this.togglePause());matchMedia(MOBILE).addEventListener?.('change',e=>{this.mobile=e.matches;this.updateMobile()});this.renderer.setAnimationLoop(t=>this.tick(t));if(this.qa){const p=new URLSearchParams(location.search);if(p.get('capture')==='1')this.dom.debug.classList.add('hidden');if(p.get('autostart')==='1')setTimeout(()=>{this.begin();this.completeCountdown()},120);setInterval(()=>{const n=performance.now();if(n-this.lastRender>70)this.tick(n)},34)}}
  initialQuality(){const q=new URLSearchParams(location.search).get('quality');if(q==='high'||q==='balanced')return q;return matchMedia(MOBILE).matches||matchMedia('(prefers-reduced-motion:reduce)').matches?'balanced':'high'}
  domRefs(){const ids=['hud','position','gap','lap','time','best','warning','minimap','speedGauge','speedArc','speed','shieldMeter','shieldText','shieldFill','boostText','boostFill','toast','quality','mute','pause','menu','start','countdown','pauseScreen','resume','pauseRestart','result','resultKicker','resultTitle','resultCopy','resultPosition','resultTime','resultSpeed','restart','mobileControls','debug','live','webglError'];return Object.fromEntries(ids.map(id=>[id,$(id)]))}
  bind(){this.dom.start.onclick=()=>{this.begin();if(!this.qa)this.audio.unlock().catch(()=>{})};this.dom.pause.onclick=()=>this.togglePause();this.dom.resume.onclick=()=>this.resume();this.dom.pauseRestart.onclick=()=>this.restart();this.dom.restart.onclick=()=>this.restart();this.dom.quality.onclick=()=>this.toggleQuality();this.dom.mute.onclick=()=>this.toggleMute()}
  reset(){this.distance=0;this.speed=0;this.lateral=0;this.lateralVel=0;this.shield=100;this.boost=65;this.elapsed=0;this.topSpeed=0;this.position=6;this.lapIndex=0;this.sector=0;this.countRemain=3;this.lastCount=0;this.goTimer=0;this.boosting=false;this.hitCooldown=0;this.hitFlash=0;this.shake=0;this.obstacleLap.clear();this.rivals.forEach((r,i)=>{r.distance=21-i*4;r.speed=0});for(const p of this.world.pickups){p.lap=-1;p.root.visible=true}for(const p of this.world.pads)p.lap=-1;const f=this.world.placeVehicle(this.world.player,0,0);this.placeRivals(0,0);this.camera.position.copy(f.center).addScaledVector(f.tangent,-13).addScaledVector(f.up,5.2);this.camTarget.copy(f.center).addScaledVector(f.tangent,10).addScaledVector(f.up,1.2);this.camera.up.copy(f.up);this.camera.lookAt(this.camTarget);this.updateHud(false)}
  menuPresentation(){this.state='menu';this.dom.menu.classList.remove('hidden');this.dom.hud.classList.add('hidden');this.dom.pauseScreen.classList.add('hidden');this.dom.result.classList.add('hidden');this.dom.countdown.classList.add('hidden');this.dom.mobileControls.classList.remove('active');this.audio.setPaused(true)}
  begin(){this.reset();this.state='countdown';this.dom.menu.classList.add('hidden');this.dom.pauseScreen.classList.add('hidden');this.dom.result.classList.add('hidden');this.dom.hud.classList.remove('hidden');this.dom.countdown.classList.remove('hidden');this.updateMobile();this.countRemain=3;this.lastCount=0;this.audio.setPaused(false);this.announce('比赛即将开始')}
  completeCountdown(){if(this.state!=='countdown')return;this.state='racing';this.speed=Math.max(this.speed,24);this.goTimer=.72;this.dom.countdown.textContent='GO';this.pulse(this.dom.countdown);this.audio.cue('go');this.toast('THRUST ONLINE');this.announce('比赛开始')}
  restart(){if(this.state==='menu'&&!this.qa)this.audio.unlock().catch(()=>{});this.audio.cue('ui');this.begin()}
  togglePause(){if(this.state==='paused'){this.resume();return}if(this.state!=='racing'&&this.state!=='countdown')return;this.beforePause=this.state;this.state='paused';this.dom.pauseScreen.classList.remove('hidden');this.dom.countdown.classList.add('hidden');this.dom.mobileControls.classList.remove('active');this.audio.setPaused(true);this.input.reset();this.announce('比赛已暂停')}
  resume(){if(this.state!=='paused')return;this.state=this.beforePause;this.dom.pauseScreen.classList.add('hidden');if(this.state==='countdown')this.dom.countdown.classList.remove('hidden');this.updateMobile();this.audio.setPaused(false);this.last=performance.now();this.announce('比赛继续')}
  toggleMute(){const m=this.audio.toggle();this.dom.mute.textContent=m?'×':'♫';this.dom.mute.ariaLabel=m?'取消静音':'静音';this.announce(m?'音效已静音':'音效已开启')}
  toggleQuality(){this.quality=this.quality==='high'?'balanced':'high';this.applyQuality();this.audio.cue('ui');this.toast(this.quality==='high'?'HIGH QUALITY':'PERFORMANCE MODE')}
  applyQuality(){const high=this.quality==='high';this.renderer.shadowMap.enabled=high;this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,high?1.65:1.15));this.bloom.enabled=high;this.bloom.strength=.56;this.bloom.radius=.48;this.bloom.threshold=.76;this.dom.quality.textContent=high?'HQ':'FX';this.dom.quality.ariaLabel=high?'切换到性能画质':'切换到高画质';this.resize()}
  updateMobile(){this.dom.mobileControls.classList.toggle('active',this.mobile&&(this.state==='racing'||this.state==='countdown'))}
  tick(now){if(this.quality==='balanced'&&this.lastRender&&now-this.lastRender<27)return;this.lastRender=now;const dt=clamp((now-this.last)/1000,0,.05);this.last=now;this.frameCount++;const t=now/1000;if(this.state==='menu')this.updateMenu(t,dt);else if(this.state==='countdown'){this.updateCountdown(dt);this.present(t,dt,{steer:0,throttle:0,brake:0,boost:false,drift:false},false)}else if(this.state==='racing')this.updateRace(t,dt);else if(this.state==='finished'||this.state==='wrecked')this.updateEnd(t,dt);else this.world.update(t,0);this.transient(dt);this.renderer.info.reset();this.composer.render(dt);if(this.qa&&this.frameCount%8===0)this.debug()}
  updateMenu(t,dt){const u=wrap01(.01+t*.0034),f=this.world.placeVehicle(this.world.player,u,Math.sin(t*.3)*.6);this.world.playerVisual(.22,Math.sin(t*.6)*.12,false,0,dt);this.rivals.forEach((r,i)=>{const p=wrap01(.04+i*.013+t*(.0048+i*.00015));this.world.placeVehicle(r.visual,p,Math.sin(t*.3+r.phase)*3.6);this.rivalVisual(r,t,dt,.45)});this.camPos.copy(f.center).addScaledVector(f.tangent,-14.5).addScaledVector(f.up,5.7).addScaledVector(f.side,Math.sin(t*.22)*2.2);this.lookPos.copy(f.center).addScaledVector(f.tangent,8.5).addScaledVector(f.up,1.1);this.smoothCamera(f,dt,2.2,58);this.world.update(t,dt);this.audio.update(.08,false,dt)}
  updateCountdown(dt){this.countRemain-=dt;const n=Math.max(1,Math.ceil(this.countRemain));if(n!==this.lastCount&&this.countRemain>0){this.lastCount=n;this.dom.countdown.textContent=n;this.dom.countdown.classList.remove('hidden');this.pulse(this.dom.countdown);this.audio.cue('countdown')}if(this.countRemain<=0)this.completeCountdown()}
  updateRace(t,dt){const input=this.input.sample(),ratio=saturate(this.speed/MAX_SPEED),boosting=input.boost&&this.boost>.4&&this.speed>18;const passive=this.speed<22?7.5:0,thrust=input.throttle*(41-ratio*14),brake=input.brake*(input.drift?30:61),drag=2.3+this.speed*.027+(Math.abs(this.lateral)>6.8?3.8:0),boostForce=boosting?62:0;this.speed+=(passive+thrust+boostForce-brake-drag)*dt;if(boosting){this.boost=Math.max(0,this.boost-24*dt);if(!this.boosting){this.audio.cue('boost');this.toast('ION OVERDRIVE')}}else this.boost=Math.min(100,this.boost+(input.throttle?4.5:7.2)*dt);this.boosting=boosting;this.speed=clamp(this.speed,0,boosting?BOOST_SPEED:MAX_SPEED+5);const steerPower=(.38+ratio*.82)*(input.drift?1.36:1),target=input.steer*(input.drift?16.5:11.2)*steerPower;this.lateralVel=damp(this.lateralVel,target,input.drift?7:10,dt);if(Math.abs(input.steer)<.05)this.lateralVel=damp(this.lateralVel,0,5,dt);this.lateral+=this.lateralVel*dt;if(Math.abs(this.lateral)>ROAD_HALF-.75){const s=Math.sign(this.lateral);this.lateral=s*(ROAD_HALF-.75);this.lateralVel*=-.18;this.speed*=.88;if(this.hitCooldown<=0)this.damage(8,'TRACK LIMIT')}this.distance+=this.speed*dt;this.elapsed+=dt*1000;this.topSpeed=Math.max(this.topSpeed,this.speed*3.6);this.hitCooldown=Math.max(0,this.hitCooldown-dt);this.hitFlash=damp(this.hitFlash,0,5.2,dt);this.shake=damp(this.shake,0,7.5,dt);const lap=Math.floor(this.distance/this.world.length);if(lap!==this.lapIndex&&lap<LAPS){this.lapIndex=lap;this.toast(`LAP ${lap+1} // PUSH`);this.boost=Math.min(100,this.boost+15);this.announce(`第 ${lap+1} 圈`)}if(this.distance>=this.world.length*LAPS){this.finish();return}this.updateRivals(t,dt);this.interactions();this.present(t,dt,input,boosting)}
  updateRivals(t,dt){for(const r of this.rivals){const gap=this.distance-r.distance,target=r.cruise+clamp(gap*.025,-4.5,5.8)+Math.sin(t*.72+r.phase)*2.1;r.speed=damp(r.speed,target,1.25,dt);r.distance+=r.speed*dt}this.position=ordinalPosition(this.distance,this.rivals.map(r=>r.distance))}
  rivalVisual(r,t,dt,ratio){r.visual.body.position.y=Math.sin(t*5.4+r.phase)*.045;r.visual.body.rotation.z=Math.sin(t*.75+r.phase)*.055;r.visual.thrusters.forEach((f,i)=>{f.scale.y=.7+ratio+Math.sin(t*18+i+r.phase)*.08;f.material.opacity=.48+ratio*.3});r.visual.pads.forEach((p,i)=>p.rotation.z+=dt*(1.4+i*.1))}
  placeRivals(t,dt){this.rivals.forEach((r,i)=>{const u=wrap01(r.distance/this.world.length),lane=clamp(r.lane+Math.sin(t*(.36+i*.018)+r.phase)*.72,-6.7,6.7);this.world.placeVehicle(r.visual,u,lane);this.rivalVisual(r,t,dt,clamp(r.speed/MAX_SPEED,.2,1))})}
  interactions(){const u=wrap01(this.distance/this.world.length),lap=Math.floor(this.distance/this.world.length);for(const o of this.world.obstacles){if(this.obstacleLap.get(o.index)===lap)continue;const longitudinal=Math.abs(shortestTrackDelta(u,o.u)*this.world.length),radius=o.kind==='barrier'?2.75:o.kind==='drones'?2.45:2.05;if(longitudinal<3.4&&Math.abs(this.lateral-o.lane)<radius){this.obstacleLap.set(o.index,lap);this.damage(o.kind==='barrier'?31:o.kind==='drones'?25:36,o.kind==='mine'?'PLASMA MINE':o.kind==='drones'?'DRONE SWARM':'ENERGY BARRIER')}}for(const p of this.world.pickups){p.root.visible=p.lap!==lap;if(p.lap===lap)continue;const long=Math.abs(shortestTrackDelta(u,p.u)*this.world.length);if(long<3.3&&Math.abs(this.lateral-p.lane)<2.05){p.lap=lap;p.root.visible=false;this.world.particles.burst(p.root.position,p.kind==='energy'?0xff55dc:0x5af4ff,25,8);if(p.kind==='energy'){this.boost=Math.min(100,this.boost+34);this.audio.cue('pickup');this.toast('ION CELL +34')}else{this.shield=Math.min(100,this.shield+28);this.audio.cue('repair');this.toast('SHIELD RESTORED')}}}for(const p of this.world.pads){if(p.lap===lap)continue;const long=Math.abs(shortestTrackDelta(u,p.u)*this.world.length);if(long<4.2&&Math.abs(this.lateral-p.lane)<3.2){p.lap=lap;this.speed=Math.min(BOOST_SPEED,this.speed+13);this.boost=Math.min(100,this.boost+20);this.world.particles.burst(p.root.position,0xff58dc,18,7,this.world.frame(p.u).up);this.audio.cue('boost');this.toast('MAG-LANE SURGE')}}for(const r of this.rivals){const ru=wrap01(r.distance/this.world.length),long=Math.abs(shortestTrackDelta(u,ru)*this.world.length),lane=clamp(r.lane+Math.sin(performance.now()*.00036+r.phase)*.72,-6.7,6.7);if(long<3.15&&Math.abs(this.lateral-lane)<2.25&&this.hitCooldown<=0){this.lateralVel+=Math.sign(this.lateral-lane||1)*6.5;r.speed*=.9;this.damage(13,'RIVAL CONTACT');break}}}
  damage(amount,source='IMPACT',force=false){if(!force&&this.hitCooldown>0)return;this.hitCooldown=.82;this.shield=Math.max(0,this.shield-amount);this.speed*=.68;this.hitFlash=1;this.shake=Math.min(1.5,this.shake+.95);const f=this.world.frame(wrap01(this.distance/this.world.length));this.world.particles.burst(this.world.player.root.position,this.shield>0?0xff6b52:0xff315b,34,13,f.up);this.audio.cue('impact');this.warn(`${source} // SHIELD ${Math.round(this.shield)}%`);if(this.shield<=0)this.wreck()}
  finish(){if(this.state==='finished'||this.state==='wrecked')return;this.position=ordinalPosition(this.distance,this.rivals.map(r=>r.distance));this.state='finished';this.audio.cue('finish');this.audio.setPaused(true);this.input.reset();this.dom.mobileControls.classList.remove('active');this.dom.countdown.classList.add('hidden');const record=!this.best||this.elapsed<this.best;if(record){this.best=this.elapsed;localStorage.setItem('neon-apex-best',String(Math.round(this.elapsed)))}this.dom.resultKicker.textContent=record?'NEW CIRCUIT RECORD':'RACE COMPLETE';this.dom.resultTitle.textContent=this.position===1?'冠军':this.position<=3?'领奖台完赛':'比赛完成';this.dom.resultCopy.textContent=this.position===1?'你征服了夜间赛道，并压制了整个 AI 车阵。':`你以第 ${this.position} 名完成三圈。更顺的走线和更晚的加速会带来更快圈速。`;this.dom.resultPosition.textContent=`${this.position} / 6`;this.dom.resultTime.textContent=formatTime(this.elapsed);this.dom.resultSpeed.textContent=`${Math.round(this.topSpeed)} KM/H`;this.dom.result.classList.remove('hidden');this.announce(`比赛完成，第 ${this.position} 名`)}
  wreck(){if(this.state==='wrecked'||this.state==='finished')return;this.state='wrecked';this.speed=0;this.audio.cue('wreck');this.audio.setPaused(true);this.input.reset();this.dom.mobileControls.classList.remove('active');this.dom.resultKicker.textContent='CRAFT DISABLED';this.dom.resultTitle.textContent='飞行器损毁';this.dom.resultCopy.textContent='护盾归零。重新调整走线，避开红色障碍并收集青色维修核心。';this.dom.resultPosition.textContent=`${this.position} / 6`;this.dom.resultTime.textContent=formatTime(this.elapsed);this.dom.resultSpeed.textContent=`${Math.round(this.topSpeed)} KM/H`;this.dom.result.classList.remove('hidden');this.announce('飞行器损毁，可以重新开始')}
  present(t,dt,input,boosting){const u=wrap01(this.distance/this.world.length),f=this.world.placeVehicle(this.world.player,u,this.lateral);this.world.playerVisual(clamp(this.speed/MAX_SPEED,0,1.35),input.steer,boosting,this.hitFlash,dt);this.placeRivals(t,dt);this.sector=Math.min(5,Math.floor(u*6));this.updateCamera(f,input.steer,boosting,dt);this.world.update(t,dt);this.audio.update(clamp(this.speed/MAX_SPEED,0,1.35),boosting,dt);this.updateHud(boosting)}
  updateCamera(f,steer,boosting,dt){const ratio=clamp(this.speed/MAX_SPEED,0,1.35);this.camPos.copy(this.world.player.root.position).addScaledVector(f.tangent,-(10.8+ratio*2.7)).addScaledVector(f.up,4.1+ratio*1.25).addScaledVector(f.side,-steer*.85);this.lookPos.copy(this.world.player.root.position).addScaledVector(f.tangent,17+ratio*12).addScaledVector(f.up,1.25);if(this.shake>0&&!this.reduced){this.camPos.addScaledVector(f.side,(Math.random()-.5)*this.shake*.32);this.camPos.addScaledVector(f.up,(Math.random()-.5)*this.shake*.32)}this.smoothCamera(f,dt,6.2,64+ratio*7.5+(boosting?5.5:0))}
  smoothCamera(f,dt,response,fov){const a=1-Math.exp(-response*dt);this.camera.position.lerp(this.camPos,a);this.camTarget.lerp(this.lookPos,a);this.camera.up.lerp(f.up,a).normalize();this.camera.fov=damp(this.camera.fov,fov,4.5,dt);this.camera.updateProjectionMatrix();this.camera.lookAt(this.camTarget)}
  updateEnd(t,dt){const u=wrap01(this.distance/this.world.length),f=this.world.placeVehicle(this.world.player,u,this.lateral,this.state==='wrecked'?.85:1.18);if(this.state==='wrecked'){this.world.player.body.rotation.z=Math.sin(t*1.7)*.08+.22;this.world.player.body.rotation.x=.08}this.placeRivals(t,dt);this.camPos.copy(f.center).addScaledVector(f.tangent,-10).addScaledVector(f.up,4.8).addScaledVector(f.side,4.5+Math.sin(t*.4));this.lookPos.copy(this.world.player.root.position).addScaledVector(f.up,.7);this.smoothCamera(f,dt,1.8,60);this.world.update(t,dt);this.updateHud(false)}
  updateHud(boosting){const km=Math.round(this.speed*3.6);this.dom.position.textContent=this.position;this.dom.lap.textContent=Math.min(LAPS,this.lapIndex+1);this.dom.time.textContent=formatTime(this.elapsed);this.dom.best.textContent=this.best?`BEST ${formatTime(this.best)}`:'BEST --:--.---';this.dom.speed.textContent=String(km).padStart(3,'0');this.dom.shieldText.textContent=`${Math.round(this.shield)}%`;this.dom.boostText.textContent=`${Math.round(this.boost)}%`;this.dom.shieldFill.style.transform=`scaleX(${saturate(this.shield/100)})`;this.dom.boostFill.style.transform=`scaleX(${saturate(this.boost/100)})`;this.dom.shieldMeter.classList.toggle('danger',this.shield<32);this.dom.speedGauge.classList.toggle('boosting',boosting);this.dom.speedArc.style.strokeDasharray=`${(clamp(km/430,0,1)*306).toFixed(1)} 411`;this.sectorEls.forEach((e,i)=>e.classList.toggle('active',i<=this.sector));const near=this.rivals.map(r=>r.distance-this.distance).sort((a,b)=>Math.abs(a)-Math.abs(b))[0]||0;this.dom.gap.textContent=Math.abs(near)<2.5?'SIDE BY SIDE':near>0?`TARGET +${(near/Math.max(1,this.speed)).toFixed(1)}s`:`GAP ${Math.abs(near/Math.max(1,this.speed)).toFixed(1)}s`;this.minimap()}
  minimap(){const c=this.ctx,w=this.dom.minimap.width,h=this.dom.minimap.height,b=this.bounds,pad=14,map=p=>[pad+(p.x-b.minX)/(b.maxX-b.minX)*(w-pad*2),pad+(p.z-b.minZ)/(b.maxZ-b.minZ)*(h-pad*2)];c.clearRect(0,0,w,h);c.beginPath();this.world.trackPoints.forEach((p,i)=>{const[x,y]=map(p);i?c.lineTo(x,y):c.moveTo(x,y)});const[sx,sy]=map(this.world.trackPoints[0]);c.lineTo(sx,sy);c.lineJoin=c.lineCap='round';c.strokeStyle='rgba(31,57,84,.92)';c.lineWidth=8;c.stroke();c.strokeStyle='rgba(88,231,255,.72)';c.lineWidth=2;c.stroke();for(const r of this.rivals){const[x,y]=map(this.world.curve.getPointAt(wrap01(r.distance/this.world.length)));c.beginPath();c.arc(x,y,3.1,0,TAU);c.fillStyle='rgba(255,94,207,.9)';c.fill()}const[x,y]=map(this.world.curve.getPointAt(wrap01(this.distance/this.world.length)));c.beginPath();c.arc(x,y,4.8,0,TAU);c.fillStyle='#f6ffff';c.shadowColor='#52f4ff';c.shadowBlur=10;c.fill();c.shadowBlur=0}
  trackBounds(){let minX=Infinity,maxX=-Infinity,minZ=Infinity,maxZ=-Infinity;for(const p of this.world.trackPoints){minX=Math.min(minX,p.x);maxX=Math.max(maxX,p.x);minZ=Math.min(minZ,p.z);maxZ=Math.max(maxZ,p.z)}return{minX,maxX,minZ,maxZ}}
  transient(dt){if(this.goTimer>0&&(this.goTimer-=dt)<=0)this.dom.countdown.classList.add('hidden');if(this.toastTimer>0&&(this.toastTimer-=dt)<=0)this.dom.toast.classList.remove('show');if(this.warningTimer>0&&(this.warningTimer-=dt)<=0)this.dom.warning.classList.remove('show')}
  toast(text,duration=1.35){this.dom.toast.textContent=text;this.dom.toast.classList.add('show');this.toastTimer=duration}
  warn(text,duration=1.75){this.dom.warning.textContent=text;this.dom.warning.classList.add('show');this.warningTimer=duration;if(this.shield<32)this.audio.cue('warning')}
  pulse(e){e.style.animation='none';void e.offsetWidth;e.style.animation=''}
  announce(text){this.dom.live.textContent='';setTimeout(()=>this.dom.live.textContent=text,20)}
  resize(){const w=Math.max(1,this.mount.clientWidth||innerWidth),h=Math.max(1,this.mount.clientHeight||innerHeight);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h,false);this.composer?.setSize(w,h)}
  snapshot(){const r=this.renderer.info.render,m=this.renderer.info.memory;return{state:this.state,quality:this.quality,elapsedMs:Math.round(this.elapsed),lap:Math.min(LAPS,this.lapIndex+1),position:this.position,speedKmh:Math.round(this.speed*3.6),shield:Math.round(this.shield),boost:Math.round(this.boost),boosting:this.boosting,lateral:Number(this.lateral.toFixed(3)),frameCount:this.frameCount,input:this.input.diagnostics(),canvas:{width:this.renderer.domElement.width,height:this.renderer.domElement.height},renderer:{calls:r.calls,triangles:r.triangles,lines:r.lines,points:r.points,geometries:m.geometries,textures:m.textures,programs:this.renderer.info.programs?.length||0,pixelRatio:this.renderer.getPixelRatio()}}}
  installDiagnostics(){const api={getState:()=>this.snapshot(),getRendererInfo:()=>this.snapshot().renderer};if(this.qa){api.actions={start:()=>this.begin(),startNow:()=>{if(this.state==='menu')this.begin();this.completeCountdown()},restart:()=>this.restart(),pause:()=>this.togglePause(),resume:()=>this.resume(),damage:(n=34)=>this.damage(n,'QA IMPACT',true),finish:()=>{this.distance=this.world.length*LAPS;this.position=1;this.finish()},wreck:()=>{this.shield=0;this.wreck()},quality:q=>{if(q==='high'||q==='balanced'){this.quality=q;this.applyQuality()}}};if(new URLSearchParams(location.search).get('capture')!=='1')this.dom.debug.classList.remove('hidden')}window.__THREE_GAME_DIAGNOSTICS__=api}
  debug(){const s=this.snapshot();this.dom.debug.textContent=[`STATE   ${s.state}`,`QUALITY ${s.quality}`,`LAP/POS ${s.lap}/${LAPS}  P${s.position}`,`SPEED   ${s.speedKmh} km/h`,`SHIELD  ${s.shield}%  BOOST ${s.boost}%`,`DRAW    ${s.renderer.calls} calls`,`TRIS    ${s.renderer.triangles.toLocaleString()}`,`MEM     ${s.renderer.geometries} geo / ${s.renderer.textures} tex`,`CANVAS  ${s.canvas.width} × ${s.canvas.height}`].join('\n')}
}

try{new Game();document.documentElement.dataset.gameReady='true'}catch(error){console.error('Neon Apex failed to initialize:',error);$('webglError').classList.remove('hidden');document.documentElement.dataset.gameReady='false'}
